channels:
  - conda-forge
  - robostack
  - robostack-staging
  - pytorch
  - nvidia
dependencies:
  - python=3.9.*
  - ros-noetic-desktop
  - ros-noetic-ros-numpy
  - catkin_tools
  - cmake
  - jupyter
  - pybind11
  - pytorch=2.0.0  # Compatibility with pytorch3d
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pip
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
    - pybullet
    - trimesh
    - pytest
    - open3d
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    - frozendict
    # Robots
    - pin==2.6.17
    # Neural networks
    - openai-clip
    - timm
    - pandas
    - mss
    # visualizations and debugging
    - matplotlib
    # Command line tools
    - click
    # data tools
    - yacs
    - h5py
    - imageio
    - pygifsicle
    - pynput
    - open3d
