channels:
  - conda-forge
  - pytorch
  - pytorch3d
  - nvidia
dependencies:
  - python==3.9.*
  - cmake
  - jupyter
  - nbconvert
  - opencv
  - pybind11
  - pinocchio
  - pytorch=1.13.*
  - pytorch-cuda=11.7
  - pytorch3d
  - pip
  - exa # optional: nice ls
  - fzf # optional: fancy ctrl + R
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
    - pybullet
    - trimesh
    - pytest
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    - frozendict
    # Neural networks
    - openai-clip
    - timm
    - pandas
    - mss
    # visualizations and debugging
    - matplotlib
    # Command line tools
    - click
    # data tools
    - yacs
    - h5py
    - imageio
    - pygifsicle
    - pynput
    - open3d
